### ISSUE TITLE
ストーリー

### ISSUE THREAD

**Issue by hdemon** [oshiete-karen/oshiete-karen#1]
階層は依存関係を示していて、子ストーリーを全て完成させたとき、親ストーリーも完成するものとします。

### Milestone 1

- [ ] カレンはユーザに、Google Calendarのスケジュールを一定の時間前に通知できる
  - [x] ユーザはカレンの操作の対象となるGoogle Calendarを発言で指定できる。
     ex. 「カレンダーを登録したい」
    - [x] bot用の証明書を発行する
    - [x] botでユーザのメッセージを受信できるようにする
      - [x] nginxでSSLの設定をする
    - [x] 登録のコマンドをパースする
    - [x] 認証のためのurlに飛ばす
    - [x] 認証されたら、トークンをDBに保存する
    - [x] --対象のcalendar_idを取得してDBに保存する--
  - [x] カレンはユーザのGoogle Calendarのスケジュールを定期的に取得できる
    - [ ] Google Calendarに更新時のcallback APIを登録する
    - [ ] callbackがあったとき、追加のスケジュール情報をDBに登録する。
  - [x] ユーザはカレンと友達になれる
    - [x] Business Centerでbotを登録する。
    - [x] 友達登録時にMIDを登録、ブロック時に削除する
  - [ ] 指定時間前になったら、DB内のスケジュール情報をユーザに通知する。
- [ ] ユーザはカレンに問い合わせることで、自分のGoogle Calendar情報を知ることができる
  - [ ] カレンはユーザの問い合わせの指示を解釈することができる
    - [ ] 日時と参照のクエリをパースする
      ex. 今日の予定を教えて
    - [ ] クエリのパターンを定義する
  - [ ] カレンはユーザの指示に従って、Google Calendarの情報を取得することができる
    - [ ] クエリに従って、DBから目的の情報を参照する。
  - [ ] カレンはユーザの指示に従って取得した情報を、ユーザに伝えることができる。
    - [ ] DBから取り出した情報をReplay API?を使ってユーザに返す
    https://business.line.me/ja/services/bot
- [ ] カレンはアイコンを持っている
  - [x] ロゴをつくる（アイコンにも流用するから
  - [ ] アイコンをデザインする
  - [ ] アイコンをbusiness centerで登録する

### Milestone 2

- [ ] ユーザはカレンに指示することで、自分のGoogle Calendarに情報を登録できる
  - [x] カレンはユーザの登録の指示を解釈することができる
    - [x] 日時をパースできる ex. 「明日の11時から12時に門谷さんと会う」
      パースに失敗したら、その部分の情報は無視する
　  タイトルはパースせずに、全文をタイトルとする
  - [ ] カレンはユーザの指示に従って、Google Calendarに情報を登録することができる
    - [ ] パースした情報を使って、Google Calendar APIを叩く
    - [ ] 登録完了・失敗をユーザに知らせる
- [ ] ユーザはカレンのLPをモバイルブラウザで見ることができる
  - [ ] LPを作る
  - [ ] ユーザはLPからカレンを友達追加できる
  - [x] Webサーバを建てる nginx

### Milestone 3 (v1.0)

- [ ] ユーザはカレンがリマインドするタイミングを発言で指定できる
  - [ ] ユーザのクエリを解釈する
  - [ ] クエリで指定されたリマインド時間をDBに格納する
- [ ] カレンはユーザの一日のGoogle Calendarのスケジュールを、指定された時間に通知できる
  - [ ] cronを使って、指定時間になったらpush APIを叩いてユーザにその日のスケジュールを知らせる。
- [ ] ユーザは毎朝のGoogle Calendarのスケジュールの通知時間を発言から指定できる
  - [ ] ユーザのクエリを解釈する
  - [ ] クエリで指定された通知時間をDBに格納する
- [ ] ユーザはカレンのプロフィール画面でカバー画像を見ることができる
 
### Milestone 4

- [ ] ユーザはカレンと対話をしつつ、スケジュールを登録したり閲覧したりできる。
- [ ] ユーザはカレンに問い合わせることで、自分のWunderlist情報を知ることができる
  - [ ] カレンはユーザの指示に従って、Wunderlistの情報を取得することができる
- [ ] ユーザはカレンの操作の対象となるWunderlistのアクセストークンをフォームから指定できる
